#
#===============================================================================
#
#         FILE:  README.pod
#
#  DESCRIPTION:  plexus.pl documentation
#
#       AUTHOR:  Daniel Bolton (), <dan at dbbo dot us>
#      COMPANY:  
#      CREATED:  18/07/2011
#     REVISION:  04/08/2011
#===============================================================================

=head1 NAME

plexus.pl - A Perl-based static site generator.

=head1 SYNOPSIS

	plexus.pl [OPTIONS]

=head1 DESCRIPTION

In Latin, I<plexus> means "twisted" or "woven". B<plexus.pl> takes a bunch of
simple, modularized files and weaves them into a static web page.

=head1 FILES

=over 4

=item * config		- Default config file location, using Config::File.
=item * config.yaml	- YAML config file, using Config::YAML.
=item * head.css	- CSS code to be included in the head.
=item * head.js		- JavaScript code to be included in the head.
=item * Here's another item.

=back

=head1 SEE ALSO

L<perldoc>, L<Config::File>,L<Config::YAML>.

=head1 COPYRIGHT

Copyright 2011 Daniel Bolton.

Permission is granted to copy, distribute and/or modify this 
document under the terms of the GNU Free Documentation 
License, Version 3.0 or any later version published by the 
Free Software Foundation; with no Invariant Sections, with 
no Front-Cover Texts, and with no Back-Cover Texts.

=cut


