#
#===============================================================================
#
#         FILE:  README.pod
#
#  DESCRIPTION:  plexus.pl documentation
#
#       AUTHOR:  Daniel Bolton (), <dan at dbbo dot us>
#      COMPANY:  
#      CREATED:  18/07/2011
#     REVISION:  04/08/2011
#===============================================================================

=head1 NAME

plexus.pl - A Perl-based static site generator.

=head1 SYNOPSIS

	plexus.pl [OPTIONS]

=head1 DEPENDENCIES

=over 4

=item * B<perl> - version 5.10 or above

=item * B<Config::File> - Debian: libconfig-file-perl

=item * B<Text::Markdown> - Debian: libtext-markdown-perl

=back

=head1 DESCRIPTION

In Latin, I<plexus> means "twisted" or "woven". B<plexus.pl> takes a bunch of
simple, modularized files and weaves them into a static web page ( so, OK, maybe it should be called I<plecto> or better yet, since it's a command, I<plecte> ).

At the time of writing, 04 August 2011, B<plexus> is far from completion and not really even ready for testing. Use at your own risk.

=head1 FILES

=over 4

=item * config		- Default config file location, using Config::File.

=item * config.yaml	- YAML config file, using Config::YAML.

=item * head.css	- CSS code to be included in the head.

=item * head.js		- JavaScript code to be included in the head.

=back

=head1 SEE ALSO

L<perldoc>, L<Config::File>,L<Config::YAML>.

=head1 COPYRIGHT

Copyright 2011 Daniel Bolton.

Permission is granted to copy, distribute and/or modify this 
document under the terms of the GNU Free Documentation 
License, Version 3.0 or any later version published by the 
Free Software Foundation; with no Invariant Sections, with 
no Front-Cover Texts, and with no Back-Cover Texts.

=cut

